export const LOGIN_REQUEST ="LOGIN_REQUEST";
export const LOGIN_SUCCESS ="LOGIN_SUCCESS";
export const LOGIN_FAIL ="LOGIN_FAIL";

export const REGISTER_USER_REQUEST ="REGISTER_USER_REQUEST";
export const REGISTER_USER_SUCCESS ="REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAIL ="REGISTER_USER_FAIL";

export const LOAD_USER_REQUEST ="LOAD_USER_REQUEST";
export const LOAD_USER_SUCCESS ="LOAD_USER_SUCCESS";
export const LOAD_USER_FAIL ="LOAD_USER_FAIL";

export const LOGOUT_SUCCESS ="LOGOUT_SUCCESS";
export const LOGOUT_FAIL ="LOGOUT_FAIL";

export const ALL_USERS_REQUEST = "ALL_USERS_REQUEST";
export const ALL_USERS_SUCCESS = "ALL_USERS_SUCCESS";
export const ALL_USERS_FAIL = "ALL_USERS_FAIL";


export const UPDATE_PROFILE_REQUEST = "UPDATE_PROFILE_REQUEST";
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_RESET = "UPDATE_PROFILE_RESET";
export const UPDATE_PROFILE_FAIL = "UPDATE_PROFILE_FAIL";

export const UPDATE_PASSWORD_REQUEST = "UPDATE_PASSWORD_REQUEST";
export const UPDATE_PASSWORD_SUCCESS = "UPDATE_PASSWORD_SUCCESS";
export const UPDATE_PASSWORD_RESET = "UPDATE_PASSWORD_RESET";
export const UPDATE_PASSWORD_FAIL = "UPDATE_PASSWORD_FAIL";

export const FORGOT_PASSWORD_REQUEST = "FORGOT_PASSWORD_REQUEST";
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_FAIL = "FORGOT_PASSWORD_FAIL";

export const RESET_PASSWORD_REQUEST = "RESET_PASSWORD_REQUEST";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAIL = "RESET_PASSWORD_FAIL";


export const CREATE_BET_REQUEST = "CREATE_BET_REQUEST";
export const CREATE_BET_SUCCESS = "CREATE_BET_SUCCESS";
export const CREATE_BET_FAIL = "CREATE_BET_FAIL";

export const ALL_BET_REQUEST = "ALL_BET_REQUEST";
export const ALL_BET_SUCCESS = "ALL_BET_SUCCESS";
export const ALL_BET_FAIL = "ALL_BET_FAIL";

export const UPDATE_BALANCE_REQUEST = "UPDATE_BALANCE_REQUEST";
export const UPDATE_BALANCE_SUCCESS = "UPDATE_BALANCE_SUCCESS";
export const UPDATE_BALANCE_RESET = "UPDATE_BALANCE_RESET";  
export const UPDATE_BALANCE_FAIL = "UPDATE_BALANCE_FAIL";

export const CREATE_DEPOSIT_REQUEST = "CREATE_DEPOSIT_REQUEST";
export const CREATE_DEPOSIT_SUCCESS = "CREATE_DEPOSIT_SUCCESS";
export const CREATE_DEPOSIT_FAIL = "CREATE_DEPOSIT_FAIL";

export const ALL_DEPOSIT_REQUEST = "ALL_DEPOSIT_REQUEST";
export const ALL_DEPOSIT_SUCCESS = "ALL_DEPOSIT_SUCCESS";
export const ALL_DEPOSIT_FAIL = "ALL_DEPOSIT_FAIL";

export const CREATE_WITHDRAWAL_REQUEST = "CREATE_WITHDRAWAL_REQUEST";
export const CREATE_WITHDRAWAL_SUCCESS = "CREATE_WITHDRAWAL_SUCCESS";
export const CREATE_WITHDRAWAL_FAIL = "CREATE_WITHDRAWAL_FAIL";

export const ALL_WITHDRAWAL_REQUEST = "ALL_WITHDRAWAL_REQUEST";
export const ALL_WITHDRAWAL_SUCCESS = "ALL_WITHDRAWAL_SUCCESS";
export const ALL_WITHDRAWAL_FAIL = "ALL_WITHDRAWAL_FAIL";

export const ALL_BETS_REQUEST = "ALL_BETS_REQUEST";
export const ALL_BETS_SUCCESS = "ALL_BETS_SUCCESS";
export const ALL_BETS_FAIL = "ALL_BETS_FAIL";

export const ALL_DEPOSITS_REQUEST = "ALL_DEPOSITS_REQUEST";
export const ALL_DEPOSITS_SUCCESS = "ALL_DEPOSITS_SUCCESS";
export const ALL_DEPOSITS_FAIL = "ALL_DEPOSITS_FAIL";

export const ALL_WITHDRAWALS_REQUEST = "ALL_WITHDRAWALS_REQUEST";
export const ALL_WITHDRAWALS_SUCCESS = "ALL_WITHDRAWALS_SUCCESS";
export const ALL_WITHDRAWALS_FAIL = "ALL_WITHDRAWALS_FAIL";


export const ALL_NOTIFICATION_REQUEST = "ALL_NOTIFICATION_REQUEST";
export const ALL_NOTIFICATION_SUCCESS = "ALL_NOTIFICATION_SUCCESS";
export const ALL_NOTIFICATION_FAIL = "ALL_NOTIFICATION_FAIL";
export const ALL_NOTIFICATION_RESET = "ALL_NOTIFICATION_RESET";


export const UPDATE_DEPOSIT_REQUEST = "UPDATE_DEPOSIT_REQUEST";
export const UPDATE_DEPOSIT_SUCCESS = "UPDATE_DEPOSIT_SUCCESS";
export const UPDATE_DEPOSIT_FAIL = "UPDATE_DEPOSIT_FAIL";
export const UPDATE_DEPOSIT_RESET = "UPDATE_DEPOSIT_RESET";


export const UPDATE_WITHDRAWAL_REQUEST = "UPDATE_WITHDRAWAL_REQUEST";
export const UPDATE_WITHDRAWAL_SUCCESS = "UPDATE_WITHDRAWAL_SUCCESS";
export const UPDATE_WITHDRAWAL_FAIL = "UPDATE_WITHDRAWAL_FAIL";
export const UPDATE_WITHDRAWAL_RESET = "UPDATE_WITHDRAWAL_RESET";


export const UPDATE_ADUSER_REQUEST = "UPDATE_ADUSER_REQUEST";
export const UPDATE_ADUSER_SUCCESS = "UPDATE_ADUSER_SUCCESS";
export const UPDATE_ADUSER_FAIL = "UPDATE_ADUSER_FAIL";
export const UPDATE_ADUSER_RESET = "UPDATE_ADUSER_RESET";


export const UPDATE_SHOWTIME_REQUEST = "UPDATE_SHOWTIME_REQUEST";
export const UPDATE_SHOWTIME_SUCCESS = "UPDATE_SHOWTIME_SUCCESS";
export const UPDATE_SHOWTIME_FAIL = "UPDATE_SHOWTIME_FAIL";
export const UPDATE_SHOWTIME_RESET = "UPDATE_SHOWTIME_RESET";

export const UPDATE_WINSET_REQUEST = "UPDATE_WINSET_REQUEST";
export const UPDATE_WINSET_SUCCESS = "UPDATE_WINSET_SUCCESS";
export const UPDATE_WINSET_FAIL = "UPDATE_WINSET_FAIL";
export const UPDATE_WINSET_RESET = "UPDATE_WINSET_RESET";


export const ALL_SHOWTIME_REQUEST = "ALL_SHOWTIME_REQUEST";
export const ALL_SHOWTIME_SUCCESS = "ALL_SHOWTIME_SUCCESS";
export const ALL_SHOWTIME_FAIL = "ALL_SHOWTIME_FAIL";

export const ALL_BETDONE_REQUEST = "ALL_BETDONE_REQUEST";
export const ALL_BETDONE_SUCCESS = "ALL_BETDONE_SUCCESS";
export const ALL_BETDONE_FAIL = "ALL_BETDONE_FAIL";
export const ALL_BETDONE_RESET = "ALL_BETDONE_RESET";


export const CREATE_SHOWHISTORY_REQUEST = "CREATE_SHOWHISTORY_REQUEST";
export const CREATE_SHOWHISTORY_SUCCESS = "CREATE_SHOWHISTORY_SUCCESS";
export const CREATE_SHOWHISTORY_FAIL = "CREATE_SHOWHISTORY_FAIL";

export const GET_SHOWHISTORY_REQUEST = "GET_SHOWHISTORY_REQUEST";
export const GET_SHOWHISTORY_SUCCESS = "GET_SHOWHISTORY_SUCCESS";
export const GET_SHOWHISTORY_FAIL = "GET_SHOWHISTORY_FAIL";

export const CREATE_SAY_REQUEST = "CREATE_SAY_REQUEST";
export const CREATE_SAY_SUCCESS = "CREATE_SAY_SUCCESS";
export const CREATE_SAY_FAIL = "CREATE_SAY_FAIL";

export const GET_SAY_REQUEST = "GET_SAY_REQUEST";
export const GET_SAY_SUCCESS = "GET_SAY_SUCCESS";
export const GET_SAY_FAIL = "GET_SAY_FAIL";






export const CLEAR_ERRORS ="CLEAR_ERRORS";

